data_root: "/data/mnist/"
train:
  batch_size: 256
  max_epochs: 500
  learning_rate: 5e-4
  num_workers: 4
mnist_transformer:
  n_classes: 10
  embed_dim: 96
  n_attention_heads: 4
  forward_mul: 2
  n_layers: 6
  n_channels: 1
  patch_size: 4
  img_size: 28

